name: Pre Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 * * * *"

jobs:
  test:
    name: Test on Node.js ${{ matrix.node_version }} - ${{ matrix.os }} ${{ matrix.os_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      matrix:
        os: 
          - ubuntu-latest
        node_version: [18,20,21]
        

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Build & Test Package
        run: |
            cd ./websf
            npm i
            npm run build
            npm link
            cd ..
            cd test
            npm i
            npm link websf
            npm run test