name: WebSF Workflow

on:
  push:
    branches:
      - main

jobs:
  pre_test:
    name: Pre-Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            path: ./
      - uses: ./.github/workflows/actions/pre-test

  npm_publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    needs: pre_test
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/npm-publish