name: WebSF Workflow

on:
  push:
    branches:
      - main

jobs:
  pre_test:
    name: Pre-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pre-Test
        uses: ./pre-test.yml

  npm_publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    needs: pre_test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: NPM Publish
        uses: ./npm-publish.yml